import React, { useState } from 'react';
import { useTranslation } from 'react-i18next';
import { FileText, Info, Download } from 'lucide-react';
import useAppStore from '../../store/useAppStore';
import { Card, CardHeader, CardTitle, CardContent } from '../ui/card';
import { Switch } from '../ui/switch';
import { Button } from '../ui/button';

export default function SummaryPanel() {
  const { t } = useTranslation();
  const { resultData, language } = useAppStore();
  const [isSimple, setIsSimple] = useState(true);

  const handleDownload = () => {
    if (!resultData) return;
    const summary = typeof resultData.summary === 'string' 
      ? resultData.summary 
      : (resultData.summary[language] || resultData.summary['en'] || '');

    const parameters = resultData.parameters || [];
    const extractedValues = resultData.extracted_values || {};

    let content = `MEDICAL REPORT ANALYSIS\n`;
    content += `======================\n\n`;
    content += `Risk Level: ${(resultData.risk_level || 'unknown').toUpperCase()}\n\n`;
    content += `SUMMARY:\n`;
    content += `${summary}\n\n`;

    if (parameters.length > 0) {
      content += `DETAILED ANALYSIS:\n`;
      parameters.forEach(p => {
        const expl = typeof p.explanation === 'string' ? p.explanation : (p.explanation[language] || p.explanation['en'] || '');
        content += `- ${p.parameter_name}: ${expl}\n`;
      });
      content += `\n`;
    }

    content += `EXTRACTED VALUES:\n`;
    Object.entries(extractedValues).forEach(([key, val]) => {
      content += `- ${key}: ${val.value || 'N/A'} ${val.unit || ''}\n`;
    });

    content += `\nGenerated on: ${new Date().toLocaleString()}\n`;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `Summary_${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  if (!resultData || !resultData.summary) return null;

  let summaryText = typeof resultData.summary === 'string' 
    ? resultData.summary 
    : (resultData.summary[language] || resultData.summary['en'] || '');

  // Simulate technical vs simple view by appending context if technical
  const displayText = isSimple 
    ? summaryText 
    : `${summaryText} Please cross-reference these findings with the complete lipid profile, hematology charts, and recent clinical history. Ongoing monitoring may be required.`;

  return (
    <Card className="glass-card mb-6 overflow-hidden">
      <div className="absolute top-0 right-0 w-32 h-32 bg-primary/5 rounded-bl-full -z-10" />
      <CardHeader className="flex flex-row items-center justify-between pb-2 border-b border-border/50 bg-muted/20">
        <CardTitle className="flex items-center gap-2 text-xl">
          <FileText className="w-5 h-5 text-primary" />
          {t('summary', 'Report Summary')}
        </CardTitle>
        <div className="flex items-center gap-3">
          <Button variant="ghost" size="sm" onClick={handleDownload} className="text-primary hover:bg-primary/10 gap-2">
            <Download className="w-4 h-4" />
            {t('download', 'Download')}
          </Button>
          <div className="h-4 w-px bg-border/50 mx-1" />
          <span className={`text-sm ${!isSimple ? 'text-primary font-medium' : 'text-muted-foreground'}`}>{t('technical_view', 'Technical')}</span>
          <Switch 
            checked={isSimple} 
            onCheckedChange={setIsSimple} 
            className="data-[state=checked]:bg-green-500"
          />
          <span className={`text-sm ${isSimple ? 'text-green-600 dark:text-green-400 font-medium' : 'text-muted-foreground'}`}>{t('simple_view', 'Simple')}</span>
        </div>
      </CardHeader>
      <CardContent className="pt-6">
        <div className="flex gap-4">
          <div className="w-1 bg-gradient-to-b from-primary/50 to-transparent rounded-full shrink-0" />
          <p className="text-lg leading-relaxed font-medium text-foreground/90 whitespace-pre-wrap">
            {displayText}
          </p>
        </div>
        {!isSimple && (
          <div className="mt-4 p-3 bg-primary/10 rounded-lg flex items-start gap-2 text-sm text-primary/80">
            <Info className="w-4 h-4 mt-0.5 shrink-0" />
            <p>Technical view provides deeper medical context generated by the AI for healthcare professionals.</p>
          </div>
        )}
      </CardContent>
    </Card>
  );
}
