import React, { useState } from 'react';
import { useTranslation } from 'react-i18next';
import { FileText, Info } from 'lucide-react';
import useAppStore from '../../store/useAppStore';
import { Card, CardHeader, CardTitle, CardContent } from '../ui/card';
import { Switch } from '../ui/switch';

export default function SummaryPanel() {
  const { t } = useTranslation();
  const { resultData, language } = useAppStore();
  const [isSimple, setIsSimple] = useState(true);

  if (!resultData || !resultData.summary) return null;

  let summaryText = typeof resultData.summary === 'string' 
    ? resultData.summary 
    : (resultData.summary[language] || resultData.summary['en'] || '');

  // Simulate technical vs simple view by appending context if technical
  const displayText = isSimple 
    ? summaryText 
    : `${summaryText} Please cross-reference these findings with the complete lipid profile, hematology charts, and recent clinical history. Ongoing monitoring may be required.`;

  return (
    <Card className="glass-card mb-6 overflow-hidden">
      <div className="absolute top-0 right-0 w-32 h-32 bg-primary/5 rounded-bl-full -z-10" />
      <CardHeader className="flex flex-row items-center justify-between pb-2 border-b border-border/50 bg-muted/20">
        <CardTitle className="flex items-center gap-2 text-xl">
          <FileText className="w-5 h-5 text-primary" />
          {t('summary', 'Report Summary')}
        </CardTitle>
        <div className="flex items-center gap-3">
          <span className={`text-sm ${!isSimple ? 'text-primary font-medium' : 'text-muted-foreground'}`}>{t('technical_view', 'Technical')}</span>
          <Switch 
            checked={isSimple} 
            onCheckedChange={setIsSimple} 
            className="data-[state=checked]:bg-green-500"
          />
          <span className={`text-sm ${isSimple ? 'text-green-600 dark:text-green-400 font-medium' : 'text-muted-foreground'}`}>{t('simple_view', 'Simple')}</span>
        </div>
      </CardHeader>
      <CardContent className="pt-6">
        <div className="flex gap-4">
          <div className="w-1 bg-gradient-to-b from-primary/50 to-transparent rounded-full shrink-0" />
          <p className="text-lg leading-relaxed font-medium text-foreground/90 whitespace-pre-wrap">
            {displayText}
          </p>
        </div>
        {!isSimple && (
          <div className="mt-4 p-3 bg-primary/10 rounded-lg flex items-start gap-2 text-sm text-primary/80">
            <Info className="w-4 h-4 mt-0.5 shrink-0" />
            <p>Technical view provides deeper medical context generated by the AI for healthcare professionals.</p>
          </div>
        )}
      </CardContent>
    </Card>
  );
}
